name: sync-defaults-with-copier
on:
  workflow_dispatch:

jobs:
  scrape:
    name: Update Copier
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Defaults with Copier
        uses: jefftriplett/actions/copier-update-action@main
        with:
          python-version: 3.9
