name: copier-copy-action
on:
  workflow_dispatch:

jobs:
  scrape:
    name: Update Copier
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Defaults with Copier
        uses: jefftriplett/actions/copier-copy-action@main
        with:
          python-version: 3.9
          copier-template-src: "gh:jefftriplett/defaults"
          copier-destination-path: "."

      - name: Commit repo contents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Adds defaults"
          push_options: --force
